### ISSUE TITLE
Pane auto closes as soon as I hit Prefix + Tab

### ISSUE THREAD

**Issue by JosephFerano** [tmux-plugins/tmux-sidebar#18]
As soon as I hit this prefix, I see the split show up and then immediately close. Is there anything in my conf that might be affecting this? I'm on OSX 10.9.5 with iTerm2, fish shell, tmux 1.9a, and tree installed.

Here's my conf;

```
# remap prefix to Control + q
set -g prefix C-s
unbind C-b
bind C-s send-prefix

# Display
set -g status-bg blue
set -g status-fg white
set -g default-terminal "screen-256color"

# Copy mode
set-option -g default-command "reattach-to-user-namespace -l fish"
setw -g mode-keys vi
bind-key -t vi-copy v begin-selection
bind-key -t vi-copy y copy-pipe "reattach-to-user-namespace pbcopy"
unbind -t vi-copy Enter
bind-key -t vi-copy Enter copy-pipe "reattach-to-user-namespace pbcopy"

# Custom bindings
bind-key x kill-pane
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
bind v copy-mode
bind Up resize-pane -U 10
bind Down resize-pane -D 10
bind Left resize-pane -L 10
bind Right resize-pane -R 10

# Open new windows/panes with current dir
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"

# Plugins
set -g @tpm_plugins "         \
  tmux-plugins/tpm            \
  tmux-plugins/tmux-open      \
  tmux-plugins/tmux-resurrect      \
  tmux-plugins/tmux-sidebar      \
"
set -g @resurrect-processes 'shh cmus weechat mutt'

# Initializes TMUX plugin manager.
# Keep this line at the very bottom of tmux.conf.
run-shell ~/.tmux/plugins/tpm/tpm

```

**Comment by jney** [comment]
looks to be a great plugin. but got this problem as well. even when changing `@sidebar-tree-pager` and `@sidebar-tree-command`. i'm using fish as default shell too.

**Comment by petermehle** [comment]
I am in the same situation. I switched to fish and the same problem appeared. Sidebar autocloses with both shortcuts, tab and backspace. $LESS is not defined neither in fish neither in bash, but sidebar appears in bash and not in fish

**Comment by bruno-** [comment]
@petermehle, thanks for reporting.

Can you please paste or link the output of `$ tmux list-keys` command?

Also, how does the output of this command look like:

    $ tree | LESS= less --dumb --chop-long-lines --tilde --IGNORE-CASE --RAW-CONTROL-CHARS

What is expected of this last command:

- the `tree` command output should be shown inside `less` pager
- less pager should "take over" the screen, not exit. In other words, after the command is executed, you should be able to press `j` or `k` to move up/down over the output

I'm going to try using `fish` in the meantime.

**Comment by petermehle** [comment]
tmux list-keys: https://dl.dropboxusercontent.com/u/1249135/keys.txt

In bash it works, in fish there is an error. Fish uses 'set' for variables

**Comment by bruno-** [comment]
I installed `fish` and tried executing the above command. This is the error I got:
```
fish: Unknown command 'LESS='. Did you mean to run less with a modified environment? Try 'env LESS= less…'. See the help section on the set
command by typing 'help set'.
tree | LESS= less --dumb --chop-long-lines --tilde --IGNORE-CASE --RAW-CONTROL-CHARS
```

So yea, prepending `env` works. Or I guess `set` would work too as you said..

I think changing this based on the `$SHELL` is a no-go. I think the likely solution will be to execute this in a sub shell like `sh -c "tree | LESS= ..."`. I'm open to other approaches..

**Comment by petermehle** [comment]
My shell skills are are pretty limited, so I am of no help unfortunately :(

BTW, great plugins, great work! They push tmux to the next level of awesomeness!

**Comment by bruno-** [comment]
Hey,
I implemented the fix and things seem to work fine with fish shell now.
Can you please pull the latest plugin version and see if everything works for you too?

> BTW, great plugins, great work! They push tmux to the next level of awesomeness!

I'm glad you like the plugins!

**Comment by petermehle** [comment]
It looks like everything works now, thx for the fix so quick :) Great!

**Comment by bruno-** [comment]
Awesome!
