### ISSUE TITLE
Enabling colourisation of tree output requires forcing

### ISSUE THREAD

**Issue by davidjb** [tmux-plugins/tmux-sidebar#20]
I'm using the latest sidebar from Git and finding that the output in the sidebar isn't coloured, whereas if I run ``tree`` (version 1.7.0) directly, it is coloured.  I added:

```
set -g @sidebar-tree-command 'tree -C'
```
to my tmux.conf and now it's forcing coloured output, which works in the sidebar.  I'm not sure what the difference here is; apparently ``tree`` considers ``$LS_COLORS``, which is already set in my environment. 

Is this a bug / should coloured output be the standard?  If not, I'd suggest adding the config line to the FAQs.

**Comment by bruno-** [comment]
Hey,
please check [here](https://github.com/tmux-plugins/tmux-sidebar/issues/18#issuecomment-62327174) on why we reverted colored tree output to plain one. In short, a user might choose another pager (example `view`) that can't interpret ansi color codes and he/she might think it's a bug.

Yes, adding a config line to FAQ in the readme is welcome. Just please make sure to mention the above limitation.

Thanks

**Comment by davidjb** [comment]
Thanks for the background, got it now.  I'll open a PR shortly!
