### ISSUE TITLE
'tree' not installed - blank sidebar

### ISSUE THREAD

**Issue by Efreak** [tmux-plugins/tmux-sidebar#22]
There's no indication that the `tree` command is required. When it's unavailable, this sidebar is simply empty. There should be some notification of such instead.

**Comment by bruno-** [comment]
Well, `tree` is not a hard requirement.. if `tree` command is not installed on the system, then a [custom tree script is used](https://github.com/tmux-plugins/tmux-sidebar/blob/master/scripts/custom_tree.sh).

However, I managed to reproduce this issue in the following way:

- `tree` installed on the system
- run tmux sidebar, sidebar ok
- uninstall `tree`
- run tmux sidebar again, sidebar in this case empty

The solution was to reload tmux plugins by reloading `tmux.conf`. When this is done, `tmux-sidebar` reloads and detects `tree` is not installed on the system anymore and uses custom tree script.
After the reloading, the sidebar was running ok with a custom script.

The core issue above is that `tree` command detection is done just on plugin startup. The benefit is speed: command detection is done only once.

Was this the issue you had, or was it some other scenario?

**Comment by Efreak** [comment]
After some further looking up, it seems that I added the -C parameter for color without trying it first without. Given this, it seems obvious now that the tree command would be required, so I'm not sure how I missed that.
