### ISSUE TITLE
Use [asciinema](asciinema.org) for demos

### ISSUE THREAD

**Issue by FranzSkuffka** [tmux-plugins/tmux-sidebar#24]
Asciinema allows you to record and embed any terminal session.
This is a way more sensible alternative to gifs (and probably youtube videos too) because of the following reasons:
- ability to copy text
- bandwidth usage
- easy markdown embedding

**Comment by bruno-** [comment]
Thanks for the heads up. It's only a pity there's no voice/sound support.

**Comment by FranzSkuffka** [comment]
@bruno and it does not record keypresses either. However I think it's great to just slam a demo into the about section.

**Comment by FranzSkuffka** [comment]
And no keystrokes either.
