### ISSUE TITLE
the sidebar window is too large when I use `PREFIX + tab`, sometimes when I use `PREFIX + Backspace `

### ISSUE THREAD

**Issue by mintisan** [tmux-plugins/tmux-sidebar#26]
when I use `PREFIX + tab`, the sidebar window is always so large :disappointed: 

<img width="1280" alt="tmux-sidebar-abnormal" src="https://cloud.githubusercontent.com/assets/9136049/12219906/42b59e24-b792-11e5-83ba-f939acbe881f.png">

sometimes when I use `PREFIX + Backspace`. 

sometimes it is normal just as below:

<img width="1280" alt="tmux-sidebar-normal" src="https://cloud.githubusercontent.com/assets/9136049/12219908/88186e10-b792-11e5-888a-e653b0338db4.png">
- OS version :  OS X EI Caption 10.11
- Tmux version : 1.9a

**Comment by i90rr** [comment]
Hi,
Here the sidebar always opens that large, also it doesn't remembers the size:
https://drive.google.com/file/d/0Bw3eycS9_SPaaE5Wd3pIWEJXdGc/view?usp=sharing

Running tmux 2.0 on GNOME Terminal 3.18.x (Fedora 23)

**Comment by avernan** [comment]
Hi,

Same here, it opens large (both tab and backspace) and doesn't remember size.
Tmux 1.9 on Debian 8.5 and Xfce 4.10. I've tried both xfce4-terminal and sakura
