### ISSUE TITLE
Bug: side bar shows file system from root on macOS

### ISSUE THREAD

**Issue by zbeekman** [tmux-plugins/tmux-sidebar#36]
I installed tmux-sidebar through tpm and it is showing me the root file system (from `/`) rather than my current working directory which is `~`. How do I fix this? Is there some refresh command that I'm missing or something?

**Comment by bruno-** [comment]
> I installed tmux-sidebar through tpm

Maybe try installing the plugin directly.. I've no idea how installation via `tpm` works.
